# Generated by Django 3.0.6 on 2020-05-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.TextField()),
                ('titulo', models.TextField()),
                ('texto', models.TextField()),
            ],
        ),
    ]
